### ISSUE TITLE
"Add support for Boolean extra-var interpretation" This future makes it impossible to pass "true" and "false" string arguments to the script

### ISSUE THREAD

**Issue by zhengyongtao** [jenkinsci/ansible-plugin#248]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 24.10

### Reproduction steps

```yaml
                        extraVars: [
                            Tony "true",
                            Alex: false,
                        ]
```
As in the example above, whether or not I add quotes to configure it as a string type, it will eventually be interpreted as a Boolean type. Causes the final parameters passed to the script to change from "true" and "false" to "True" and "False"

### Expected Results

Correct pass string types "true" and "false"

### Actual Results

The final parameters passed to the script to change from "true" and "false" to "True" and "False"
